import type { Metadata } from "next"
import {Inter} from 'next/font/google'
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  weight: ['300','400', '500', '600', '700'],  // Adjust weights as needed
  variable: '--font-inter-display',
});

export const metadata: Metadata = {
  title: "Perumnas Real Estate",
  description: "Generated by @rotgauz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
